# device
gpu_id: [0]
# exp
exp_path: ./exp_outputs/exp_outputs_shanghaiA #./exp_outputs/SHA_SFAoatt
exp_name: SHA_SFAoatt
# dataset
data_mode: SHA
if_dedata: False
# net
net: SFAoatt_gate_alone  #  SFAoatt_fcgate
# resume
if_resume: False
#resume_path: ./exp_outputs/SHA_SFAoatt/10-25_14-28_SHA_SFAoatt/latest_state.pth
# pretrain
if_pretrain: True
pretrained_path: ./exp_outputs/exp_outputs_shanghaiA/08-25_16-40_SHA_SFAoatt/all_ep_230_mae_60.7_mse_102.2.pth
  #./exp_outputs/exp_outputs_shanghaiA/10-12_17-10_SHA_SFAoatt/all_ep_681_mae_30.2_mse_64.3.pth
  #./exp_outputs/exp_outputs_shanghaiA/08-05_09-27_SHA_SFAoatt/all_ep_236_mae_60.5_mse_103.3.pth
#./exp_outputs/SHA_SFAoatt/04-30_11-53_SHA_SFAoatt/all_ep_529_mae_61.6_mse_99.6.pth
# reporduction
seed: 3035  # random seed for reporduction
# learning rate
lr: 0.0001  # learning rate
lr_decay: 1  # decay rate  1
lr_decay_start: -1
num_epoch_lr_decay: 0.95
# train and val
val_batchsize: 1 # must be
train_batchsize: 8
MAX_EPOCH: 1000
if_print: False
if_vis_results: False
vis_train_result: False
PRINT_FREQ: 1 # 30
VAL_FREQ: 1 # 10 # each epoch
VAL_DENSE_START: 1
# optimizer
optimizer: Adam #Adam
SGD:
  momentum: 0.995
# loss
vector_loss: False
use_my_loss: wmyloss_cos # False











